import { Subject } from "@/types";

export const MOCK_SUBJECTS: Subject[] = [
  // Computer Science
  {
    id: 1,
    code: "CS101",
    name: "Introduction to Programming",
    department: "Computer Science",
    description: "Fundamentals of programming using problem-solving and algorithmic thinking.",
    createdAt: "2026-01-15T08:00:00Z",
  },
  {
    id: 2,
    code: "CS201",
    name: "Data Structures and Algorithms",
    department: "Computer Science",
    description: "Study of efficient data organization, algorithms, and computational complexity.",
    createdAt: "2026-01-15T08:00:00Z",
  },
  {
    id: 3,
    code: "CS301",
    name: "Database Management Systems",
    department: "Computer Science",
    description: "Design, implementation, and management of relational database systems.",
    createdAt: "2026-01-15T08:00:00Z",
  },

  // Information Technology
  {
    id: 4,
    code: "IT101",
    name: "Computer Fundamentals",
    department: "Information Technology",
    description: "Introduction to computer hardware, software, and operating systems.",
    createdAt: "2026-01-15T08:00:00Z",
  },
  {
    id: 5,
    code: "IT202",
    name: "Web Systems and Technologies",
    department: "Information Technology",
    description: "Development of modern web applications using front-end and back-end technologies.",
    createdAt: "2026-01-15T08:00:00Z",
  },
  {
    id: 6,
    code: "IT303",
    name: "Network Administration",
    department: "Information Technology",
    description: "Configuration, management, and security of computer networks.",
    createdAt: "2026-01-15T08:00:00Z",
  },

  // Business Administration
  {
    id: 7,
    code: "BA101",
    name: "Principles of Management",
    department: "Business Administration",
    description: "Overview of management functions, leadership, and organizational behavior.",
    createdAt: "2026-01-15T08:00:00Z",
  },
  {
    id: 8,
    code: "BA201",
    name: "Marketing Management",
    department: "Business Administration",
    description: "Concepts and strategies for identifying customer needs and market opportunities.",
    createdAt: "2026-01-15T08:00:00Z",
  },
  {
    id: 9,
    code: "BA302",
    name: "Financial Management",
    department: "Business Administration",
    description: "Principles of financial planning, budgeting, and investment decision-making.",
    createdAt: "2026-01-15T08:00:00Z",
  },
    {
      id: 10,
      code: "CS302",
      name: "Software Engineering",
      department: "Computer Science",
      description: "Principles and practices of software development, testing, and maintenance.",
      createdAt: "2026-01-15T08:00:00Z",
    },
    {
      id: 11,
      code: "CS401",
      name: "Artificial Intelligence",
      department: "Computer Science",
      description: "Introduction to intelligent systems, machine learning, and problem-solving techniques.",
      createdAt: "2026-01-15T08:00:00Z",
    },
    {
      id: 12,
      code: "IT304",
      name: "Cybersecurity Fundamentals",
      department: "Information Technology",
      description: "Core concepts of information security, risk management, and cyber threats.",
      createdAt: "2026-01-15T08:00:00Z",
    },
    {
      id: 13,
      code: "IT305",
      name: "Cloud Computing",
      department: "Information Technology",
      description: "Introduction to cloud service models, deployment strategies, and virtualization.",
      createdAt: "2026-01-15T08:00:00Z",
    },
    {
      id: 14,
      code: "IT306",
      name: "Mobile Application Development",
      department: "Information Technology",
      description: "Design and development of mobile applications for Android and cross-platform environments.",
      createdAt: "2026-01-15T08:00:00Z",
    },
    {
      id: 15,
      code: "BA303",
      name: "Business Analytics",
      department: "Business Administration",
      description: "Application of data analysis techniques for business decision-making.",
      createdAt: "2026-01-15T08:00:00Z",
    },
    {
      id: 16,
      code: "BA304",
      name: "Human Resource Management",
      department: "Business Administration",
      description: "Management of workforce planning, recruitment, training, and employee relations.",
      createdAt: "2026-01-15T08:00:00Z",
    },
    {
      id: 17,
      code: "BA305",
      name: "Entrepreneurship",
      department: "Business Administration",
      description: "Development of entrepreneurial skills, innovation strategies, and business planning.",
      createdAt: "2026-01-15T08:00:00Z",
    },
    {
      id: 18,
      code: "CS402",
      name: "Computer Networks",
      department: "Computer Science",
      description: "Study of network architectures, communication protocols, and network security.",
      createdAt: "2026-01-15T08:00:00Z",
    },
    {
      id: 19,
      code: "IT307",
      name: "Systems Integration and Architecture",
      department: "Information Technology",
      description: "Techniques for integrating software systems and designing enterprise architectures.",
      createdAt: "2026-01-15T08:00:00Z",
    },
];